/* Durable in-app daily briefing; external delivery remains intentionally deferred. */
(function () {
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
  const money = value => Number(value || 0).toLocaleString('en-BD', { maximumFractionDigits: 2 });
  const content = () => document.getElementById('executiveSummaryContent');
  const generateButton = () => document.getElementById('btnGenerateExecutiveSummary');
  const render = payload => {
    const summary = payload.summary;
    generateButton().hidden = !payload.can_generate;
    if (!summary) { content().innerHTML = '<div class="corrigendum-empty">The first daily briefing will be generated by the background worker. Executives can generate it now.</div>'; return; }
    const attention = (summary.needs_attention || []).map(item => `<li><strong>${esc(item.tender_id)}</strong> · ${esc(item.title)}<small>${esc(item.detail)}</small></li>`).join('') || '<li>No blocked or overdue preparation work recorded.</li>';
    content().innerHTML = `<div class="outcome-learning-kpis"><article class="outcome-learning-kpi"><small>Active pipeline</small><strong>${summary.active_pipeline}</strong><span>${summary.pipeline_total} total pipeline items</span></article><article class="outcome-learning-kpi"><small>Open attention</small><strong>${summary.blocked_tasks + summary.overdue_tasks}</strong><span>${summary.blocked_tasks} blocked · ${summary.overdue_tasks} overdue</span></article><article class="outcome-learning-kpi"><small>Decisioned win rate</small><strong>${summary.win_rate_pct == null ? '—' : `${summary.win_rate_pct}%`}</strong><span>${summary.won_bids} won · ${summary.lost_bids} lost</span></article><article class="outcome-learning-kpi"><small>Awarded value</small><strong>৳${money(summary.awarded_contract_value)}</strong><span>${summary.submitted_pending} awaiting decision</span></article></div><div class="executive-attention"><strong>Needs attention</strong><ul>${attention}</ul><small>Generated ${esc(summary.generated_at || summary.summary_date)} · ${esc(summary.generated_by || 'scheduler')}</small></div>`;
  };
  async function load() { if (!window.TenderApiService || !localStorage.getItem('tenderpulse_access_token')) { content().innerHTML = '<div class="corrigendum-empty">Sign in with an authorized role to view the daily briefing.</div>'; generateButton().hidden = true; return; } try { render(await window.TenderApiService.getExecutiveKpiSummary()); } catch (error) { content().innerHTML = `<div class="corrigendum-empty">Executive briefing unavailable: ${esc(error.message)}</div>`; generateButton().hidden = true; } }
  async function generate() { const button = generateButton(); button.disabled = true; try { render(await window.TenderApiService.generateExecutiveKpiSummary()); } catch (error) { alert(`Could not generate briefing: ${error.message}`); } finally { button.disabled = false; } }
  document.addEventListener('DOMContentLoaded', () => { document.getElementById('btnRefreshExecutiveSummary')?.addEventListener('click', load); generateButton()?.addEventListener('click', generate); window.tenderStore?.subscribe('authChange', load); window.refreshExecutiveSummary = load; load(); });
}());
