"""Durable executive operating summaries generated by the background worker."""
import json
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

from backend.models import BidOutcomeModel, BidPipelineItemModel, BidPreparationTaskModel, ExecutiveKpiSummaryModel


def _as_datetime(value: Optional[str]) -> Optional[datetime]:
    if not value:
        return None
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
        return parsed.astimezone(timezone.utc).replace(tzinfo=None) if parsed.tzinfo else parsed
    except (TypeError, ValueError):
        return None


def serialize_executive_summary(summary: Optional[ExecutiveKpiSummaryModel]) -> Optional[Dict[str, Any]]:
    if not summary:
        return None
    try:
        attention = json.loads(summary.needs_attention_json or "[]")
    except json.JSONDecodeError:
        attention = []
    return {
        "summary_date": summary.summary_date, "pipeline_total": summary.pipeline_total,
        "active_pipeline": summary.active_pipeline, "overdue_tasks": summary.overdue_tasks,
        "blocked_tasks": summary.blocked_tasks, "submitted_pending": summary.submitted_pending,
        "decisioned_bids": summary.decisioned_bids, "won_bids": summary.won_bids,
        "lost_bids": summary.lost_bids, "win_rate_pct": summary.win_rate_pct,
        "awarded_contract_value": summary.awarded_contract_value, "needs_attention": attention,
        "generated_by": summary.generated_by,
        "generated_at": summary.generated_at.isoformat() if summary.generated_at else None,
    }


def ensure_daily_executive_summary(db, now: Optional[datetime] = None, generated_by: str = "scheduler", force: bool = False) -> Tuple[ExecutiveKpiSummaryModel, bool]:
    """Create today's summary once, unless an authorized operator requests a refresh."""
    now = now or datetime.utcnow()
    summary_date = now.date().isoformat()
    existing = db.query(ExecutiveKpiSummaryModel).filter(ExecutiveKpiSummaryModel.summary_date == summary_date).first()
    if existing and not force:
        return existing, False

    pipelines = db.query(BidPipelineItemModel).all()
    tasks = db.query(BidPreparationTaskModel).all()
    outcomes = db.query(BidOutcomeModel).all()
    overdue = [task for task in tasks if task.status != "done" and (_as_datetime(task.due_date) and _as_datetime(task.due_date) < now)]
    blocked = [task for task in tasks if task.status == "blocked"]
    won = sum(1 for outcome in outcomes if outcome.status == "won")
    lost = sum(1 for outcome in outcomes if outcome.status == "lost")
    submitted = sum(1 for outcome in outcomes if outcome.status == "submitted")
    decisioned = won + lost
    awarded = sum(float(outcome.awarded_contract_value or 0) for outcome in outcomes if outcome.status == "won")
    attention: List[Dict[str, str]] = []
    for task in blocked[:5]:
        attention.append({"type": "blocked_task", "tender_id": task.tender_id, "title": task.title, "detail": task.blocker or "Blocked preparation task"})
    for task in overdue[:5]:
        attention.append({"type": "overdue_task", "tender_id": task.tender_id, "title": task.title, "detail": f"Due {task.due_date}"})
    if existing:
        summary = existing
    else:
        summary = ExecutiveKpiSummaryModel(summary_date=summary_date)
        db.add(summary)
    summary.pipeline_total = len(pipelines)
    summary.active_pipeline = sum(1 for item in pipelines if item.stage not in {"won", "lost"})
    summary.overdue_tasks = len(overdue)
    summary.blocked_tasks = len(blocked)
    summary.submitted_pending = submitted
    summary.decisioned_bids = decisioned
    summary.won_bids = won
    summary.lost_bids = lost
    summary.win_rate_pct = round(won / decisioned * 100, 1) if decisioned else None
    summary.awarded_contract_value = round(awarded, 2)
    summary.needs_attention_json = json.dumps(attention)
    summary.generated_by = generated_by
    summary.generated_at = now
    db.flush()
    return summary, True
